lidars:
  - name: "front_lidar"
    topic: "/lidar/front/points"
    pose:
      x: 1.0
      y: 3.0
      z: 0.82
      roll: 0.0
      pitch: 0.0
      yaw: 0.0
    height: 0.82
    num_lasers: 8
    alpha_begin: -14.0
    alpha_end: 14.0
    laser_range: 25.0
    horizontal_step: 0.0174533

  - name: "rear_lidar"
    topic: "/lidar/rear/points"
    pose:
      x: -2.0
      y: -3.0
      z: 0.82
      roll: 0.0
      pitch: 0.0
      yaw: 0.0
    height: 0.82
    num_lasers: 8
    alpha_begin: -14.0
    alpha_end: 14.0
    laser_range: 10.0
    horizontal_step: 0.0174533
