trunk_detector_node:
  ros__parameters:
    input_topic: /merged_cloud
    output_topic: /detector_output

    grid_size: 0.4               # размер ячейки 2D-сетки, м
    height_threshold: 0.05       # порог высоты объекта, м
    min_intensity: 0.00          # шумовые точки по интенсивности
    max_distance: 40.0           # радиус обработки, м
